```groovy
pipeline {
    agent any

    tools {
        maven 'MAVEN'
        jdk 'JDK'
    }


    stages {

        stage('Initialize') {
            steps {
                echo "Java Home: ${JAVA_HOME}"
                echo "Maven Home: ${M2_HOME}"

                bat 'java -version'
                bat 'mvn -version'
            }
        }

        stage('Build') {
            steps {
                dir('my-app') {
                    bat 'mvn -B -DskipTests clean package'
                }
            }
        }
    }

    post {
        always {
            junit(
                testResults: 'my-app/target/surefire-reports/*.xml',
                allowEmptyResults: true
            )
			echo "Successfully passed"
        }
    }
}
